### ISSUE TITLE
Tiny typo

### ISSUE THREAD

**Issue by alexey-wk** [korsajan/gocatboost#1]
I think there is a typo https://github.com/korsajan/gocatboost/blob/343da6d9792b23bbb0c207b8a6fc2f4d1a721fb7/catboost_wrapper.go#L70

By the way, it's a very useful lib!

**Comment by korsajan** [comment]
Thank you for pointing that out, @alexey-wk ! I appreciate your feedback. I've fixed the typo in [this commit](https://github.com/korsajan/gocatboost/commit/983a31296af0c420e25501c95be2339fb371975f). I'm glad you find the library useful!
